version: "3.3"

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: "unijobs"
      MYSQL_USER: "unijobs"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

